apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-bot
  template:
    metadata:
      labels:
        app: incident-bot
    spec:
      containers:
      - name: bot
        image: yourdockerhub/incident-bot:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
